### ISSUE TITLE
Question about version constraints

### ISSUE THREAD

**Issue by wsyski** [liferay/liferay-npm-build-tools#173]
I have upgraded your example 
<pre>git@github.com:izaera/liferay-npm-bundler-2-example.git</pre> 
to angular 6. Everything works fine. I have a clean console log. However when I examine:
<pre>http://localhost:8080/o/js_loader_modules</pre>

I can see many errors like:
<pre>
"npm-angular5-provider$rxjs@6.2.2/Scheduler": {
  "dependencies": [M, E, R, "npm-angular5-provider$rxjs-compat/Scheduler"],
  "map": {"npm-angular5-provider$rxjs-compat": ":ERROR:Missing version constraints for npm-angular5-provider$rxjs-compat in package.json of npm-angular5-provider$rxjs@6.2.2"}
},

"npm-angular5-provider$rxjs@6.2.2/add/operator/mapTo": {
  "dependencies": [M, E, R, "npm-angular5-provider$rxjs-compat/add/operator/mapTo"],
  "map": {"npm-angular5-provider$rxjs-compat": ":ERROR:Missing version constraints for npm-angular5-provider$rxjs-compat in package.json of npm-angular5-provider$rxjs@6.2.2"}
},
</pre>
Is it something I can disregard? What does it depend on?

**Comment by izaera** [comment]
That simply means that the `package.json` file in `npm-angular5-provider$rxjs@6.2.2` is not declaring any version constraints for the `rxjs-compat` package, but some of its modules are requiring modules from `rxjs-compat`. 

For instance, in the first example you pasted `npm-angular5-provider$rxjs@6.2.2/Scheduler` is requiring something from `npm-angular5-provider$rxjs-compat` but ``npm-angular5-provider$rxjs@6.2.2`'s package.json does not have any version constraint for `npm-angular5-provider$rxjs-compat`.

Is that bad? Probably... Or may be not. It depends on whether you use those modules at all. Some npm packages ship JS files intended to be run in node.js, for example, that when deployed to a web environment won't work. You can also have packages with `peerDependencies` that you are failing to satisfy, test modules that assume some tools are present, build scripts, ...

If you don't get any error in the console.log I wouldn't bother too much unless you know for sure that you are going to need those modules in the future.

If you see that you don't need those modules and want to remove such messages just exclude the offending modules from the bundler build by using the `.npmbundlerrc` file.

**Comment by wsyski** [comment]
Thanks

**Comment by izaera** [comment]
`true` means exclude everything. So, for example:

```
"exclude": {
  "rxjs": true
}
```

means `exclude all packages named rxjs no matter what version`.

If instead of `true` you use an array, it must contain glob expressions of files inside the packages to be excluded. For example:

```
"exclude": {
  "rxjs@1.0.0": ['**/*.ts', 'README.md']
}
```

means `exclude the file README.md and all files ending with .ts in the package rxjs at version 1.0.0`.

**Comment by wsyski** [comment]
Thanks for very explanatory answer. I have tried to add .npmbundlerr in npm-angular5-provider:
<pre>
"exclude": {
        "rxjs-compat": true
    }
</pre>
But I still get 
<pre>
"npm-angular5-provider$rxjs@6.2.2/add/operator/throttle": {
  "dependencies": [M, E, R, "npm-angular5-provider$rxjs-compat/add/operator/throttle"],
  "map": {"npm-angular5-provider$rxjs-compat": ":ERROR:Missing version constraints for npm-angular5-provider$rxjs-compat in package.json of npm-angular5-provider$rxjs@6.2.2"}
},
</pre>
I would expect rxjs-compat excluded. What did I do wrong?
Another question - why do we need in  .npmbundlerrc of npm-angular5-portlet-say-hello:
<pre>
"exclude": {
        "*": true
    },
</pre>

**Comment by izaera** [comment]
@wsyski You don't need to exclude `rxjs-compat` but `rxjs`, which is the package that has issues. However, you need to make sure that you won't need that package if you want to exclude it completely. If it is there, it is probably needed for something...

Regarding the `"*": true` in `npm-angular5-portlet-say-hello` it is there because, as you are importing everything from the provider, you don't need any npm package at all in `npm-angular5-portlet-say-hello` JAR. That exclusion speeds up the build and makes `npm-angular5-portlet-say-hello` smaller. Otherwise, the whole angular would be included in the JAR (because it is listed as dependencies in the package.json) but it wouldn't be used during runtime => a waste of time and space.

**Comment by wsyski** [comment]
Thanks. That answers all my questions
