### ISSUE TITLE
Can we make the the sending of analytics optional?

### ISSUE THREAD

**Issue by brunobasto** [liferay/liferay-npm-build-tools#180]
I'm not sure but I have the feeling this could be making the build take longer than needed. Here is an output from my command line:

```
time npm run bundler

> dynamic-data-mapping-form-web@2.0.0 bundler /Users/brunobasto/Projects/liferay-portal/modules/apps/dynamic-data-mapping/dynamic-data-mapping-form-web
> liferay-npm-bundler

Bundling 30 dependencies...
Bundling took 4s
npm run bundler  5.43s user 0.53s system 19% cpu 30.879 total
```

As you can see, it says the bundling process took only 4secs, but the process hangs and takes actually 30 secs, in some cases even more. I'm not sure the cause of it is the analytics request, just a guess taking a quick look at the code.

**Comment by izaera** [comment]
@brunobasto It shouldn't because we have disabled analytics in the portal with the `LIFERAY_NPM_BUNDLER_NO_TRACKING` env variable (which is set by the gradle plugin before running npm 👉 https://github.com/liferay/liferay-portal/blob/65059440dfaf2b8b365a20f99e83e4cdb15478aa/modules/sdk/gradle-plugins-defaults/src/main/java/com/liferay/gradle/plugins/defaults/internal/NodeDefaultsPlugin.java#L95).

However, if you run it from outside (directly with npm) you won't get such var and it will delay your times, for sure. 

Also, there's the possibility that the setup is not working properly... Can you add the `time` command to the `build` script in `package.json` and run `gradle deploy` instead to make sure you are reproducing the exact thing? 

Thx.

**Comment by brunobasto** [comment]
Hey @izaera, I'm not running from gradle most of the time. I didn't know about LIFERAY_NPM_BUNDLER_NO_TRACKING, that help a lot. Thanks.

**Comment by izaera** [comment]
@brunobasto there are some other alternatives in addition to the env var (a CLI arg and a config file) 👉 https://github.com/liferay/liferay-npm-build-tools/issues/118#issuecomment-392785239
