### ISSUE TITLE
Question regarding build process

### ISSUE THREAD

**Issue by micduffy** [liferay/liferay-npm-build-tools#235]
Hello,

Thanks very much for fixing the windows compatibility.

I am attempting to make a webpack build so that I can serve the component in an environment.

I know about lnbs-start - but it seems to be blocking.

Is there any sub-command that can be invoked in the build process to generate the webpack files ? Or should I just run npm run build and publish the jar ?

Thanks in advance for any advice you can offer.

Thanks again,

Mike.

**Comment by izaera** [comment]
> I am attempting to make a webpack build so that I can serve the component in an environment.

Can you elaborate a bit more? The webpack build that `lnbs-start` does is targeted at live reload during development, not intended to be used for production. Also, if you are going to deploy with webpack, why using the bundler? 🤔

**Comment by micduffy** [comment]
This is a good point. The intention was to run the npm / portlet outside of liferay for testers. But youre right, why not just deploy it and have them test it natively.

**Comment by izaera** [comment]
Yes, that sounds better. 

But even if you still wanted to deploy it as a webpack bundle I recommend using your own config file and bundling scripts, instead of relying on `lnbs-start`. That is because the "contract" behind `npm run start` is that you get live reloads for development, but we may change the implementation in the future if we see it is necessary. 

I mean, we are using webpack with a configuration but we may change that config in the future and it would break your production build (if you relied on it). We could even change `lnbs-start` so that it doesn't use webpack.

I'm closing this. Feel free to reopen it if you have any further doubt :-).
