### ISSUE TITLE
Current generator requires Liferay JS Portlet Extender version 1.1.0

### ISSUE THREAD

**Issue by travisrcory** [liferay/liferay-npm-build-tools#248]
Hey guys,

Excited about the new features added in. I noticed that the current portlet created by the generator will require version 1.1.0 of Liferay JS Portlet Extender. I noticed that [marketplace](https://web.liferay.com/en/marketplace/-/mp/application/115543020) only has version 1.0.0. I know that this isn't an issue with the generator specifically, I just wanted to point that out. Thanks again!

**Comment by izaera** [comment]
Yes, we are aware of that. We will publish a new version of the extender in about 2-3 weeks because we want to ship it with more functionalities. However, it requires version 1.1.0 only if you use settings configuration. Otherwise it should ask for 1.0.0 as is explained [here](https://github.com/liferay/liferay-npm-build-tools/wiki/.npmbundlerrc-file-reference#create-jarfeaturesjs-extender).
