### ISSUE TITLE
node generate-samples.js cannot find file or directory .generator-liferay-bundle.json

### ISSUE THREAD

**Issue by john-co** [liferay/liferay-npm-build-tools#249]
node generate-samples.js 
fs.js:646
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: ENOENT: no such file or directory, open '/home/john-co/.generator-liferay-bundle.json'
    at Object.fs.openSync (fs.js:646:18)
    at fs.readFileSync (fs.js:551:33)
    at readJsonSync (/home/john-co/Liferay/public/liferay-npm-build-tools/packages/generator-liferay-bundle/node_modules/read-json-sync/index.js:42:14)
    at Object.<anonymous> (/home/john-co/Liferay/public/liferay-npm-build-tools/packages/generator-liferay-bundle/qa/generate-samples.js:14:20)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)

**Comment by izaera** [comment]
Mmm, you should probably have that file anyway, because we are requiring some variable that points to Liferay's dir so that the samples can be deployed:

<img width="517" alt="imagen" src="https://user-images.githubusercontent.com/3273630/50206625-3e6a0e80-036c-11e9-82a1-02ee0f5530cb.png">

If you want to change that because it is not suitable for CI I need to know where to get that value (environment, detection routine that hardcodes it for CI, ...). 

I can also avoid the error and if the variable is not set generate the samples without configuring the deployment.

**Comment by yuchi** [comment]
(Pssst, @izaera, you can use https://carbon.now.sh to share screenshots of code — text selection is preserved too)

**Comment by john-co** [comment]
> Mmm, you should probably have that file anyway, because we are requiring some variable that points to Liferay's dir so that the samples can be deployed:
> 
> <img alt="imagen" width="517" src="https://user-images.githubusercontent.com/3273630/50206625-3e6a0e80-036c-11e9-82a1-02ee0f5530cb.png">
> 
> If you want to change that because it is not suitable for CI I need to know where to get that value (environment, detection routine that hardcodes it for CI, ...).
> 
> I can also avoid the error and if the variable is not set generate the samples without configuring the deployment.

How can I obtain the json file? and if you don't think it's necessary for functional testing let's ignore it.

**Comment by izaera** [comment]
I don't know if it is necessary for functional testing. Are you deploying the projects to a Liferay instance? If yes, then you need the file. If not, then we can ignore it.

These are the contents of the file:

```json
{
        "sdkVersion": "/Users/ivan/Liferay/Javascript/liferay-npm-build-tools",
        "answers": {
                "facet-deploy": {
                        "liferayPresent": true,
                        "liferayDir": "/Users/ivan/Liferay/CE/bundles"
                }
        }
}
```

The `sdkVersion` should point to the folder where `liferay-npm-build-tools` lives. You can use a relative path if you want because the `generator-liferay-bundle` is in fact inside `liferay-npm-build-tools`.

The `liferayDir` must point to your CI's Liferay instance so that when you run `npm run deploy` in the generated projects they are deployed to that instance and let you run the functional tests afterwards.

**Comment by john-co** [comment]
could we upload the .generator-liferay-bundle.json file within the lfieray-npm-build-tools repo and target it there? It doesn't seem to make sense for someone to know on their own to generate the contents of the file and place it outside of repo structure.

**Comment by izaera** [comment]
Define "necessary" ;-). It's necessary to run the QA tests in a specific machine, not for the project itself.

However, we cannot commit it because it has two fields (`sdkVersion` and `liferayDir`) which are dependant on your environment. So, if I upload the file working in my environment, it won't work on yours, neither in the CI, and so on...

**Comment by john-co** [comment]
For testing, I'm planning to deploy the projects to liferay instance. So, since the two fields will be dependent on the environment, I'll have the QA test generate the file and contents specific to the machine environment.

To your point, it's true it's not really "necessary" for the project. It was just weird to me because I didn't see documentation on how to create the file for testing.

**Comment by izaera** [comment]
> To your point, it's true it's not really "necessary" for the project. It was just weird to me because I didn't see documentation on how to create the file for testing.

Mmmm, that's true, but since this is something internal to the project I don't think it is worth documenting it in the wiki because it would add noise. Maybe we can put it in the README inside the qa folder. If you like that place feel free to send a PR with whatever documentation you think may help QA people :-).

**Comment by john-co** [comment]
Yes, that will be helpful to have in the qa folder. I'll include it in the PR. :)
