### ISSUE TITLE
if i just run yo liferay-bundle and create a react app, how do i know which version of Liferay Portal this supports?

### ISSUE THREAD

**Issue by lawrence-lee** [liferay/liferay-npm-build-tools#307]
I've only just followed the steps in the wiki to create a react app. https://github.com/liferay/liferay-npm-build-tools/wiki/How-to-use-generator-liferay-bundle#run-the-generator

**Comment by izaera** [comment]
Normally, all versions of Liferay support all features unless otherwise stated, meaning we try to backport everything to previous versions and/or make things backwards compatible.

Also, features that need higher versions of any component, include constraints in the code so that they cannot be deployed or executed if any dependency is missing. For example, [configuration](https://github.com/liferay/liferay-npm-build-tools/wiki/Configuring-pure-javascript-projects#configuration) needs `JS Portlet Extender` >= `1.1.0` as stated in the docs so, any portlet with configuration support won't start unless that version or a higher one is present.

Also, you can manually tweak the needed version using [create-jar.features.js-extender](https://github.com/liferay/liferay-npm-build-tools/wiki/.npmbundlerrc-file-reference#create-jarfeaturesjs-extender) entry in your `.npmbundlerrc` file.

**Comment by lawrence-lee** [comment]
As I'm reading through the create-jar.features.js-extender link, I have another question. If `true` is provided, how does the bundler determine the minimum version? Is that through the `liferayDir` in the `.npmbuildrc`? Or does my bundle need to be running?

**Comment by izaera** [comment]
No. It determines it based on the features you have in your project.

In fact, `true` is the default and that's why you get errors like:

```
org.osgi.framework.BundleException: Could not resolve module: myreact [993]_  Unresolved requirement: Require-Capability: osgi.extender; filter:="(&(osgi.extender=liferay.frontend.js.portlet)(version>=1.0.0))"_ [Sanitized]
```
when you deploy a portlet with some feature that needs the JS portlet extender, for example.  

Or if you use [configuration support](https://github.com/liferay/liferay-npm-build-tools/wiki/Configuring-pure-javascript-projects#configuration) it will complain if you don't have portlet extender version >= 1.1.0

**Comment by lawrence-lee** [comment]
Thanks!
