### ISSUE TITLE
Can I create more than one portlet per project?

### ISSUE THREAD

**Issue by pedrodelg** [liferay/liferay-npm-build-tools#319]
Hi! I've created a react js npm project with yeoman. 

The project created works very well, now my problem is that I want to create another portlet inside the project I've been created. 

¿How do i do that? Is there a comand line to create another portlet inside a project?

**Comment by izaera** [comment]
Hi @pedrodelg:

Currently we only support one portlet per project, when using pure Javascript portlets, because having more than one would make setup much more complex and the cost-benefit doesn't seem to be worth the effort.

So, you have two options:

1. Create another project.
2. Switch to a gradle based build (using [blade](https://dev.liferay.com/es/develop/tutorials/-/knowledge_base/7-1/blade-cli), for example) where you can create as many portlets as you want inside the same project.

Given that 2 adds complexity and requires a mixed frontend/backend developer role, I would recommend going with 1.

If you need to share packages between the two portlets you can create an extra project that exports shared npm packages and then import them from the portlets. Make sure to read the blog posts explaining the _imports_ technique ([here](https://github.com/liferay/liferay-npm-build-tools/wiki/Miscellaneous-resources#blog-posts)) and don't hesitate to ask again if there's anything you don't understand.

**Comment by jbalsas** [comment]
To expand on what @izaera said, nothing prevents you from simply creating a "folder" (project) and inside run the generator as many times as you wish to generate as many widgets as necessary!
