### ISSUE TITLE
UMD pattern broken when portal exposes Loader’s define

### ISSUE THREAD

**Issue by yuchi** [liferay/liferay-npm-build-tools#57]
If a module is written using the common UMD format it will try to define itself and therefore breaking since it’s already inside an AMD define factory call.

The UMD pattern:

```js
(function (root, factory) {
    if (typeof define === 'function' && define.amd) {
        // !!! Passes !!!
        define([], factory);
    } else if (typeof module === 'object' && module.exports) {
        // Doesn’t pass here
        module.exports = factory();
    } else {
        // Doesn’t pass here
        root.returnExports = factory();
  }
}(typeof self !== 'undefined' ? self : this, function () {
    return { answer: 12 }; // Factory
}));
```

The UMD pattern after transpilation and bundling (and dead code elimination for clarity):

```js
Liferay.Loader.define('pkg@1.2.3/path/to/module.js', [ 'module' ], function (module) {
  // if (typeof define === 'function' && define.amd) {
    define([], function () {
      return { answer: 12 }; // Factory
    });
  // }
});
```

The result is that a consumer would get the initial, empty (!!) `module.exports` object sine the factory is actually never called.

```js
require('pkg@1.2.3/path/to/module.js', function (thing) {
  console.log(thing); // Logs: {}
});
```

- - -

By disabling the _System Settings › JavaScript Loader › Expose global_ configuration everythign works correctly since there’s no global `define` anymore.

**Comment by yuchi** [comment]
I foresee 2 different approaches:

1. giving module factories a specific `define` implementation so that they can use it to give the exports; `</over-engineering-mode>`
2. shadowing the global define with a well placed `const define = undefined` at the start of the file. `</troll-modules-mode>`

**Comment by izaera** [comment]
Hi @yuchi 

If your module already has AMD format (and UMD counts as AMD 😉) you just need to use the [babel-preset-liferay-amd](https://github.com/liferay/liferay-npm-build-tools/tree/master/packages/babel-preset-liferay-amd) instead of the standard one when processing it with liferay-npm-bundler.

We do it in the jquery example, for instance (see https://github.com/liferay/liferay-blade-samples/blob/4d477ab52fa04ad91dd283ef37796182a08b7461/gradle/apps/npm/jquery-npm-portlet/.npmbundlerrc#L2 )

Hope that fixes it 🙏

**Comment by yuchi** [comment]
It doesn’t. Steps to reproduce:

1. Start with `blade create -t npm-portlet`
2. Install lodash
3. Import lodash
4. Doesn’t work

**Comment by izaera** [comment]
O_o `npm-portlet` does not use the AMD preset, but the standard one 👉 https://github.com/liferay/liferay-blade-samples/blob/4d477ab52fa04ad91dd283ef37796182a08b7461/gradle/apps/npm/simple-npm-portlet/.npmbundlerrc#L2

I know it would be much friendlier not to have to configure these things, but that would need some kind of smart autodetection of what npm modules use. That would need to be done by looking at the JS AST and guessing what people is trying to do, which would lead to false positives, negatives, and would need maintenance. 

I'm not saying that it is impossible, but it is an effort (probably a big one) and we would have to prioritize it. I'm not sure if it would fit in the current backlog (@jbalsas ?).

**Comment by izaera** [comment]
To add some more info: the main problem I see with autodetection of UMD modules is that the prolog @yuchi pasted can be present/absent/slightly modified/heavily modified, depending on the developer.

For example, jquery (I think it is) calls `define()` near the end of a file, in a heavily nested `if()` statement.

**Comment by izaera** [comment]
On the other hand, having an autodetection feature (or perhaps just a map of `{npm packages: needed preset}`) would help to reuse knowledge among the community, so that if some user detects that some package needs a specific preset, the rest will leverage that knowledge automagically in the next version of liferay-npm-bundler.

I'm not sure how well would that scale, though... 🤔 It probably would converge to something useful if enough users leverage liferay-npm-bundler and the used npm packages universe is restricted.

**Comment by yuchi** [comment]
I was a little bit rude on that comment. Let me explore the issue a little bit further.

I am not loading an AMD module, but a UMD module that is a perfectly valid CommonJS ***and** AMD module.

The current situation makes using UMD impossible in a CommonJS ecosystem. Since exposing the modules as UMD is something publishers could do at any time (even in non breaking releases) as an additional feature, that means that previously working modules simply stop working.

Let me restate the issue: UMD modules get confused by being in an AMD context (global define/require) but the bundler expects them to have become an AMD-ified pure CommonJS module.

Even adding this would solve the problem **without any autodetect feature**:

```js
define.amd = true;
function define(factory) {
  module.exports = factory();
}
```

or even:

```js
const define = { amd: false };
```

**Comment by izaera** [comment]
Hi again:

I have tried to reproduce the `lodash` issue. I do:

1. blade create -t simple-npm-portlet my-portlet
2. Install lodash 4.17.4
3. Import lodash
4. Modify .npmbundlerrc to the following:

```
{
    "preset": "liferay-npm-bundler-preset-standard",
    "lodash@4.17.4" : {
        "plugins": [
            "replace-browser-modules"
        ],
        ".babelrc": {
            "presets": ["liferay-amd"]
        }
    }
}
```

5. It works

@yuchi, I think we are not understanding each other because we are discussing about ways to fix it while the real discussion that should take place is how we want it to work.

As I said in my previous comments, with the current tooling you can make it work (as seen in the previous `.npmbundlerrc`). The only thing that needs to be done is to use a different preset for UMD modules (a preset that doesn't wrap the module into a `Liferay.define` call). That way, the lodash javascript files remain unwrapped and only the `define()` call is tweaked so that the UMD export works seamlessly and uses the correct module name and Liferay's loader:

![image](https://user-images.githubusercontent.com/3273630/32717151-e470d6e2-c858-11e7-857b-239a848c76a8.png)

Now that we know it works, we can argue if making it work looks complex or not. From my point of view, we should make this easier given that, as you said, any package developer may choose to export it as UMD even in a version change and that would break the build and make it hard to debug. 

Also, having to manually tune all your UMD packages if your build has UMD and non-UMD packages looks quite cumbersome.

This is were the autodetector feature is convenient, because the build's wrapping plugin ([babel-plugin-wrap-modules-amd](https://github.com/liferay/liferay-npm-build-tools/tree/master/packages/babel-plugin-wrap-modules-amd)) would detect that a module is in UMD format and decide not to wrap it. 

This way there would be no need to configure anything in `.npmbundlerrc`.

**Comment by izaera** [comment]
I still can see one problem: what happens if you don't expose Liferay AMD loader and the UMD code gets fooled into thinking that it is inside a CommonJS environment.

We could "fix" it by namespacing the `define.amd` tests too, changing them to Liferay.Loader.define.amd too 🤔.

**Comment by izaera** [comment]
This should not happen again with the bundler 2.x approach as all UMD modules are fooled into thinking that they are inside CommonJS as per [this injected code](https://github.com/liferay/liferay-npm-build-tools/blob/master/packages/babel-plugin-wrap-modules-amd/src/index.js#L8).
