### ISSUE TITLE
Liferay bundler/loader issue with @angular/common/http

### ISSUE THREAD

**Issue by wsyski** [liferay/liferay-npm-build-tools#80]
I have upgraded angular to 5.2.4. Tried to use
<pre>@angular/common/http</pre>

Liferay AMD loader tries to load. 
<pre>http://<host>@angular/common@5.2.4/http.js?languageId=en_US</pre>

The problem seems to be with
<pre>__CONFIG__</pre>
variable since it does not resolve 
<pre>@angular/common@5.2.4/http</pre>

It looks like the liferay loader/bundler does not handle the case when there are 2 modules in the same catalogue:
<pre>@angular/common/bundles/common.umd.js</pre>
<pre>@angular/common/bundles/common-http.umd.js</pre>

I think that the same issue is with 
<pre>@angular/platform-browser/animations</pre>

**Comment by herlazp** [comment]
Having also an issue when using `@angular/common/http` with the bundler

Dependencies involved are 
 `@angular@4.4.6
rxjs@5.5.6`

and latest version for the bundler
`liferay-npm-bundler@1.4.2`


So we have dependencies resolving without any trouble

`http://localhost:8080/combo/?browserId=other&minifierType=&languageId=en_US&b=7010&t=1510142035968&/o/js/resolved-module/rxjs@5.4.1/observable/ConnectableObservable.js&/o/js/resolved-module/@angular/core@4.4.6/bundles/core.umd.js `

But when trying to resolve those at `@angular/common/http`, 

`http://localhost:8080/combo/?browserId=other&minifierType=&languageId=en_US&b=7010&t=1510142035968&/o/js/resolved-module@angular/common@4.4.6/http.js  `

We can see the resource is loaded in a wrong syntax, pointing to `@angular/common@4.4.6/http.js `instead of the right one at `@angular/common@4.4.6/bundles/common-http.umd.js` , where the dependency is located.

The bundler seems to generate the .js properly, been able to access it at
`.../o/js/resolved-module/@angular/common@4.4.6/bundles/common-http.umd.js`
and seen it at `js_loader_modules`.

In my case, this failure only comes to surface when using modules from the `@angular/common/http` dependency.

**Comment by izaera** [comment]
Hi there. We are working on a stabilization round right now and we'll be fixing some issues with peerDependencies and version resolution. As soon as we have that ready, we will tackle Angular 5.

So, it's going to take some time, but it is definitely in the schedule.

Also, I will inform if there's any workaround for this after diagnosing the problem. The detailed info you have both provided will definitely help. Thanks :-).

**Comment by wsyski** [comment]
Thanks. Is there any workaround with version 1.4.2?

**Comment by izaera** [comment]
Not that I know. We haven't tested Angular 5 yet :-(.

You can try to use the newly released version 1.5.0 that generates an HTML report with all the operations performed by the bundler and perhaps you can narrow the issue further down...

**Comment by wsyski** [comment]
I have tested 1.60 with angular 5.2.9. Everything is fine until I start using HttpClientModule. I get exactly the same error when trying to load:
Cannot GET /@angular/common@5.2.9/http.js?languageId=en_US
This is the same error as in 1.4.2

**Comment by izaera** [comment]
Hi @wsyski. 

Sorry for the delay, but the problems turned out to be more difficult than we thought at first :-(.

We are very near to releasing a new 2.x version of the bundler where we change the philosophy of package resolution dramatically and that will fix all the issues we were having with `peerDependencies` (which are very used by Angular) in versions 1.x of the bundler.

If you want (and can) you can upload a ZIP file with your project so that I can test it before release (which will occur probably next week) and make sure everything works as expected.

Would you be willing to upload such ZIP? 

Thx,
Ivan

**Comment by izaera** [comment]
🤔 I have deployed npm-test-error.zip to current master version and I get a different error:

<img width="603" alt="imagen" src="https://user-images.githubusercontent.com/3273630/39692405-0ff4663c-51e1-11e8-9d1d-8e07960bf20f.png">

Strange.

I'm going to test with the new bundler and see if it works correctly.

**Comment by izaera** [comment]
OK. So I have tried the setup with the new `liferay-npm-bundler` (version series `2.x.x`) and it fails in `tslib` because the UMD code gets fooled. I'll fix that and release a new canary version until we release the definitive `2.0.0` version.

I think I will not fix this bug (at least for now) in the `1.x.x` series of the bundler as it had some problems when managing `peerDependencies` (which Angular uses pervasively) and we will encourage developers to switch to `2.x.x` series soon.

I'm creating https://github.com/liferay/liferay-npm-build-tools/issues/111 to fix the UMD error in series `2.x.x` and closing this as a resolved question.

However, I will write in this issue the canary version that needs to be used and the modifications needed to make the project work.

Thanks for the feedback @wsyski :-).

**Comment by izaera** [comment]
I have released version `1.7.0-alpha.6d6b0c8b` (a prerelease canary version for series `2.x.x` of the bundler).

To make the project work just point `liferay-npm-bundler` to that version in your `package.json` and remove the `"module": "amd"` option of `tsconfig.json` and that should make it.
